export const jokeTopics = [
  "The latest social media trend",
  "Aliens and UFOs",
  "Cryptocurrency and blockchain",
  "Artificial intelligence gone wild",
  "The absurdity of modern diets",
  "Current political scandals",
  "Historical figures in today's world",
  "The tech billionaire lifestyle",
  "Iconic artists and their scandals",
  "Musicians caught in bizarre situations",
  "Movies that would never get made today",
  "Books banned for being too outrageous",
  "TV shows with unexpected plot twists",
  "The life of a meme",
  "Celebrity pets with more followers than us",
  "The future of humanity (or lack thereof)",
  "Dark humor about the end of the world",
  "The dating life of robots",
  "Conspiracy theories that are too wild to believe",
  "The existential crisis of a self-driving car",
  "Intergalactic travel mishaps",
  "Time travel paradoxes",
  "The secret life of emojis",
  "What if animals could vote?",
  "The philosophy of breakfast cereals",
  "The hidden meanings behind corporate logos",
  "What if plants had social media?",
  "Famous philosophers debating fast food",
  "Reality TV for robots",
  "The diary of an overworked cloud",
  "Ancient gods in the modern workforce",
  "If historical battles were decided by video games",
  "The secret society of left socks",
  "Superheroes on a budget",
  "The existential dread of self-checkout machines",
  "Zombies learning to code",
  "If your pet could sue you for neglect",
  "The first contact with aliens via TikTok",
  "The world's most boring superpower",
  "Ghosts with day jobs",
  "The art of procrastination in different cultures",
  "A day in the life of a WiFi signal",
  "The great debate: pineapple on pizza or not?",
  "If landmarks could speak, what would they say?",
  "The fashion sense of mythical creatures",
  "The untold story of background characters in movies",
  "What if your car had an attitude?",
  "The emotional life of a paperclip",
  "Celebrity chefs cooking for cavemen",
  "The Olympics for inanimate objects",
  "The secret society of garden gnomes",
  "If historical battles were fought with food",
  "The drama of office supplies",
  "Superheroes on a reality TV show",
  "The untold story of autocorrect",
  "What if your fridge could talk (and judge)",
  "The secret lives of traffic cones",
  "Dinosaurs in modern office jobs",
  "The hidden world of sock drawers",
  "Quantum physics explained by a toddler",
  "The existential dread of a paperclip",
  "Famous philosophers at a modern party",
  "The mating rituals of Wi-Fi signals",
  "The secret diary of a shopping cart",
  "If kitchen utensils formed a band",
  "The melodrama of printer ink",
  "What if your alarm clock had feelings?",
  "Celebrity interviews with inanimate objects",
  "The bureaucratic life of a passport",
  "The mid-life crisis of a coffee machine",
  "The hidden talents of street signs",
  "If your toothbrush could tell stories",
  "The secret society of lost buttons",
  "The existential crisis of a rubber band",
  "A day in the life of a public restroom",
  "The love life of a charging cable",
  "If your houseplants could gossip",
  "The hidden agenda of elevator music",
  "The secret society of lost remotes",
  "The melodrama of a teabag's life",
  "The political views of a recycling bin",
  "If your lawnmower was a philosopher",
  "The secret agent life of a lightbulb",
  "The drama of a sneeze in public",
  "The untold story of a pencil's eraser",
  "The existential dread of a bookmark",
  "The secret diary of a subway seat",
  "The hidden world behind vending machines",
  "The philosophical musings of a garden hose",
  "If your washing machine could complain",
  "The rise of AI in everyday life",
  "The metaverse mishaps",
  "The drama of smart home devices",
  "The existential crisis of NFTs",
  "Influencers in space",
  "The absurdity of viral TikTok challenges",
  "The privacy invasion by smart speakers",
  "The meme-ification of politics",
  "The secret life of Zoom backgrounds",
  "The irony of self-driving cars getting lost",
  "The hidden world of Instagram filters",
  "The daily struggles of a WiFi password",
  "The secret society of reusable bags",
  "The great debate: work-from-home vs. office life",
  "The existential dread of a smartphone battery",
  "The hidden lives of delivery drones",
  "The absurdity of microtransactions in games",
  "The undercover life of a QR code",
  "The impact of cancel culture on fictional characters",
  "The secret diary of a streaming service",
  "The melodrama of cloud storage",
  "The fashion trends set by video game characters",
  "The hidden agenda of autocorrect",
  "The philosophical debates in AI chatbots",
  "The secret society of lost AirPods",
  "The existential crisis of a social media like button",
  "The melodrama of a 5G network",
  "The untold story of a smartwatch's notifications",
  "The hidden talents of a robot vacuum",
  "The political views of a voice assistant",
  "The dating life of a virtual reality avatar",
  "The secret life of electric vehicle charging stations",
  "The irony of smart fridges running out of food",
  "The conspiracy theories around streaming algorithms",
  "The existential dread of a fitness tracker",
  "The drama of a social media outage",
  "The secret society of e-waste",
  "The daily life of an emoji",
  "The melodrama of a virtual meeting",
  "The hidden world of blockchain transactions",
  "The philosophical musings of a smart thermostat",
  "The secret diary of a cybersecurity breach",
  "The irony of robots needing software updates",
  "The undercover life of a security camera",
  "The existential crisis of a 404 error",
  "The secret society of USB ports",
  "The melodrama of a forgotten password",
  "The hidden agenda of a pop-up ad",
  "The philosophy behind spam emails",
  "The secret life of a hashtag",
  "The great debate: real vs. synthetic meat in the lab",
  "The real reason people go to the gym",
  "The secret sex lives of politicians",
  "Why your boss might be into BDSM",
  "The inappropriate uses of office supplies",
  "What your grandma really does at bingo night",
  "The hidden meanings behind nursery rhymes",
  "The confessions of a naughty librarian",
  "The most awkward family reunion moments",
  "Why priests might need Tinder",
  "What really happens during a 'business trip'",
  "The truth about clowns and their after-hours activities",
  "The dirty secrets of the PTA",
  "The inappropriate uses for a selfie stick",
  "Why your therapist might need therapy",
  "The confessions of a wedding planner",
  "What happens when the lights go out at church",
  "The real reason for those late-night infomercials",
  "The unwritten rules of bathroom graffiti",
  "The untold stories of a gynecologist's diary",
  "The secret life of a proctologist",
  "The most inappropriate times to use vibrators",
  "Why your parents' sex life is the stuff of nightmares",
  "The dirty little secrets of Disney characters",
  "The confessions of a hotel housekeeper",
  "The real reason people join book clubs",
  "What happens in the janitor's closet",
  "The most awkward moments in sex ed class",
  "The confessions of a divorce lawyer",
  "The inappropriate uses of a garden hose",
  "Why your pet might need a therapist too",
  "The dirty side of yoga positions",
  "The secret sex life of your favorite cartoon character",
  "The confessions of a mortician",
  "What really goes on at retirement homes",
  "The most inappropriate places to get frisky",
  "The truth about those 'team-building' exercises",
  "Why chefs might be into food play",
  "The confessions of a flight attendant",
  "The inappropriate uses of a massage table",
  "The real reason for those long bathroom breaks at work",
  "The dirty secrets behind kids' TV shows",
  "The most awkward moments at a nude beach",
  "What your teacher does after school",
  "The confessions of a wedding crasher",
  "Why your neighbor might be into voyeurism",
  "The inappropriate applications of VR",
  "The confessions of a personal trainer",
  "The dirty side of farm life",
  "The truth about those 'innocent' sleepovers",
  "Why your doctor might need a drink after your visit",
];
